version: '3'
services:
  redis:
    image: redis:6.2.6-alpine
    ports:
      - '6379:6379'
  redisCommander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
